# Generated by Django 5.1.1 on 2024-09-29 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
