# Generated by Django 5.1.1 on 2024-09-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0004_profile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='condition',
            new_name='problemsInput',
        ),
    ]
