# Generated by Django 5.1.1 on 2024-10-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0008_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
